<?php

namespace App\Http\Requests;

use App\Rules\CheckPasswordRule;
use App\Rules\EmailCheckingRule;
use App\Rules\UniqueForAdmin;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class editUserRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title'            =>  'required',
            'id'            =>  'required',
            'first_name'    =>  'required',
            'last_name'     =>  'required',
            'email'         =>  ['required',new UniqueForAdmin()],
            'country'       =>  'required',
            'new_password'  =>[],

            'old_password'  =>  [new CheckPasswordRule($this->id,$this->new_password)]

        ];
    }
    public function messages()
    {
        // TODO: Change the autogenerated stub
        return[
            'first_name.required'   =>  'First Name field is required.'
        ];
    }
}
