<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class resetPassword extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'password'  =>'required',
            'confirmpassword'   =>  'same:password',
            'token' => 'exists:password_resets,token'
        ];
    }
    public function messages()
    {
       // TODO: Change the autogenerated stub
        return[
          'confirmpassword.same'=>'The confirm password and password must match'
        ];
    }
}
